"""initial tables

Revision ID: 93903694d417
Revises: 
Create Date: 2021-06-10 16:36:06.137506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93903694d417'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('locker',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('zipcode', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('staffed', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_locker_zipcode'), 'locker', ['zipcode'], unique=False)
    op.create_table('ask',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_updated', sa.DateTime(), nullable=True),
    sa.Column('item_url', sa.String(), nullable=True),
    sa.Column('item_name', sa.String(), nullable=True),
    sa.Column('item_asin', sa.String(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('code', sa.String(length=4), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'PURCHASED', 'DELIVERED', name='askstates'), nullable=True),
    sa.Column('locker_id', sa.Integer(), nullable=True),
    sa.Column('asker_email', sa.String(length=120), nullable=True),
    sa.Column('buyer_email', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['locker_id'], ['locker.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('note',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('ask_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=1400), nullable=False),
    sa.Column('is_order_number', sa.Boolean(), nullable=True),
    sa.Column('is_locker_code', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['ask_id'], ['ask.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_note_date_created'), 'note', ['date_created'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_note_date_created'), table_name='note')
    op.drop_table('note')
    op.drop_table('ask')
    op.drop_index(op.f('ix_locker_zipcode'), table_name='locker')
    op.drop_table('locker')
    # ### end Alembic commands ###
