"""initial tables

Revision ID: daca375de800
Revises: 
Create Date: 2021-07-18 22:44:10.651775

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'daca375de800'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ask',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('item_url', sa.String(), nullable=True),
    sa.Column('item_name', sa.String(), nullable=True),
    sa.Column('item_asin', sa.String(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('code', sa.String(length=4), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'PURCHASED', 'DELIVERED', name='askstates'), nullable=True),
    sa.Column('locker_place_id', sa.String(), nullable=False),
    sa.Column('asker_email', sa.String(length=120), nullable=True),
    sa.Column('buyer_email', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('note',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('ask_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=1400), nullable=False),
    sa.Column('type', sa.Enum('SIMPLE_MESSAGE', 'ORDER_NUMBER', 'LOCKER_CODE', name='notetypes'), nullable=True),
    sa.ForeignKeyConstraint(['ask_id'], ['ask.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_note_created'), 'note', ['created'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_note_created'), table_name='note')
    op.drop_table('note')
    op.drop_table('ask')
    # ### end Alembic commands ###
